server:
  port: 9000

spring:
  datasource:
    generate-unique-name: false
    name: myauthserver
  security:
    basic:
        enabled: true
        authorize-mode: NONE
    user:
      name: paul
      password: 123